### ISSUE TITLE
Blank app after install

### ISSUE THREAD

**Issue by viejopala** [RichardGrac/SmartADMIN#7]
After clone and run npm install and run ionic serve the app is blank and show these errors

![image](https://user-images.githubusercontent.com/359763/50601063-db12cd00-0e91-11e9-9859-3fb4a5d0427f.png)

With this **ionic info**
![image](https://user-images.githubusercontent.com/359763/50601203-42c91800-0e92-11e9-96fb-77c82e1bdad1.png)

**Comment by RichardGrac** [comment]
I’m aware! I’m gonna check it today afternoon. Thank you!

If you’re interested in the final product:
https://smartadminproject.herokuapp.com

Regards!

El 2 ene 2019, a la(s) 10:26, viejopala <notifications@github.com<mailto:notifications@github.com>> escribió:


After clone and run npm install and run ionic serve the app is blanck and show these errors

[image]<https://user-images.githubusercontent.com/359763/50601063-db12cd00-0e91-11e9-9859-3fb4a5d0427f.png>

**Comment by RichardGrac** [comment]
Now it's working correctly

**Comment by viejopala** [comment]
Solved! Thanks!!
